## STARTING IN NumPy

In [1]:
import numpy as np # Numpy must be installed, in Python console: >>>install numpy

#### Creating function to print pretty 3D arrays :)

In [36]:
# I tried to do a generic recursive method for any dimensions, 
# but I can't assign array's subset values ([x,y,z,...,:]) to print by this way! :(
def print3d(array):
    # Prove array is 3D
    if array.ndim != 3:
        print('Not a 3D array!')
        return
    # Printing
    for line in array:
        print(*[item[:] for item in line]) # Column wides aren't regular!

Important notes:<br>
- Some methods usually return a new array, so transformations and modifications won't be done on original array. However, sort() , ravel(), transpose(), for example, have an effect on original array.
- When we work with an array's slice or subsetting, changes made on the second one will affect to the original array!

#### Creating arrays

In [83]:
# Create two arrays to test basic operations with them
array_1 = np.arange(4) # From a range
array_2 = np.array([4,5,6,7,8,9]) # From a list
print(array_1)
print(array_2)

[0 1 2 3]
[4 5 6 7 8 9]


In [79]:
# Other examples
print('--- Other examples ---')
print(np.arange(10,25,5)) # From 10 to 25 (not incuded), step=5
print(np.zeros(4))
print(np.ones(4))
print(np.empty((2,2))) # 2x2 array full of 1. values
print(np.ones((2,2), dtype = int)) # Specifying dtype

print('\n')
print(np.linspace(0,2,9)) # From 0 to 2, 9 values evenly spaced
print(np.full((2,2),7)) # 2 rowns, 2 columns, full of 7

print('\n')
print(np.eye(2,2)) # 2x2 identity matrix
print(np.eye(3,2)) # Matrix isn't squared, so it hasn't a 'perfect' diagonal 

print('\n')
print(np.random.random((3,6))) # 3x6 matrix full of random values between 0-1
print(np.around(np.random.random((3,6)),decimals=2)) # Rounding decimal numbers

--- Other examples ---
[10 15 20]
[0. 0. 0. 0.]
[1. 1. 1. 1.]
[[1. 1.]
 [1. 1.]]
[[1 1]
 [1 1]]


[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
[[7 7]
 [7 7]]


[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]
 [0. 0.]]


[[0.52161476 0.46131699 0.47284479 0.49346328 0.07888736 0.69703361]
 [0.8291497  0.27148068 0.06213377 0.94509917 0.30528563 0.9529835 ]
 [0.18941224 0.04038036 0.94910198 0.15792104 0.93807394 0.14042437]]
[[0.71 0.64 0.78 0.84 0.48 0.36]
 [0.36 0.85 0.14 0.27 0.   0.3 ]
 [0.05 0.7  0.09 0.46 0.59 0.07]]


#### Formating and Printing arrays

In [55]:
# TO ASSIGN GENERAL PRINT OPTIONS (APPLIED TO ALL DE CODE):
np.set_printoptions(precision=4) # Number precision = 3
# suppress = False # Suppresses use of scientific notation for small numbers
# formatter = {'float': '{: 0.3f}'.format})  # Give format to floats
# suppress_small = True # Suppresses small numbers


# TO APPLY OPTIONS ONLY TO A SPECIFIC CODE FRAGMENT
with np.printoptions(precision=3, suppress=True, formatter={'float': '{: 0.3f}'.format}):
    print(np.ones((2,2)))
    
# TO APPLY OPTIONS TO A PRINT
array_to_print = np.random.random((2,2))
print(np.array_str(array_to_print, precision=1, suppress_small=True))

# FORMATING
print(np.around(array_to_print,decimals=2))

[[ 1.000  1.000]
 [ 1.000  1.000]]
[[0.4 0.2]
 [1.  0. ]]
[[0.4399 0.1634]
 [0.9959 0.0027]]


#### Reshaping arrays
array.shape -> Attribute, not a method! Because NumPy arrays are **inmutable** <br>
array.reshape() -> Returns a **new array** since  NumPy arrays are inmutable <br>

In [6]:
print(array_1.shape) # array_1 shape: (4,) 4*? (it's like it would have only 1 dimension)
array_1b = array_1.reshape(-1,1) # new array from array_1 with modified shape: 4*(automatically adjust)
print(array_1b)
print(array_1b.shape)
array_1c = array_1b.reshape(1,-1) # new array from array_1b with initial shape of array_1 (automatically adjust)*4
print(array_1c) 
print(array_1c.shape)
print(array_2.reshape(2,3))

(4,)
[[0]
 [1]
 [2]
 [3]]
(4, 1)
[[0 1 2 3]]
(1, 4)
[[4 5 6]
 [7 8 9]]


#### Inspecting array attributes

In [9]:
print(len(array_1)) # Length (total elements, it not depends on its dimensions)
print(len(array_1b))
print(array_1.shape)
print(array_1.ndim) # Dimensions
print(array_1b.ndim)
print(array_1.size) # Length (total elements, it not depends on its dimensions)
print(array_1b.size)

print(array_1.dtype) # Data type (NumPy has its own data types)
print(array_1.dtype.name) # dtype.name is a str
print(array_1.dtype.type) # dtype is the 'class'

array_float = np.array([0.0,1,2,3]) # If any element is float, array's dtype=float and every item becomes float
print(array_float.dtype) 
print(array_float.dtype.type)  
print(array_float)

print(array_1.astype(float))
print(array_float.astype(int))
print(array_1.astype(bool)) # Numbers can be converted to boolean: 0=False !0=True
print(array_float.astype(bool))
print(array_1.astype(str)) # Numbers to str
print(array_1.astype(complex)) # Int to complex numbers
print(array_1.astype(complex).astype(str)) # Int to complex numbers to str

4
4
(4,)
1
2
4
4
int32
int32
<class 'numpy.int32'>
float64
<class 'numpy.float64'>
[0. 1. 2. 3.]
[0. 1. 2. 3.]
[0 1 2 3]
[False  True  True  True]
[False  True  True  True]
['0' '1' '2' '3']
[0.+0.j 1.+0.j 2.+0.j 3.+0.j]
['0j' '(1+0j)' '(2+0j)' '(3+0j)']


#### Operating with arrays

In [69]:
# CREATE 2 ARRAYS TO WORK WITH (with 'compatible' number of rows and cols)
basic_array = np.arange(12) # Basic array with 3*4 items (to create 3x4 and 4x3 matrix from it)
print('Array 3x4')
a3x4 = basic_array.reshape(3,-1)
print(a3x4.shape)
print(a3x4)
print('Array 4x3')
a4x3 = a3x4.reshape(a3x4.shape[1],-1) # rows = cols of array_3x4 (more convenient if we don't know array size)
print(a4x3.shape)
print(a4x3)
print('Array 3x4 full of 1')
one3x4=np.ones((a3x4.shape[0],a3x4.shape[1]))
print(one3x4)

# TEST ARITHMETIC OPERATIONS WITH ARRAYS

print('\n -- BASIC ARITHMETIC OPERATIONS --')
#print(np.substract(a3x4,one3x4)) # Error: NumPy doesn't has substract() function 

# We can operate array-array or array-number 
# ARRAY-NUMBER : Operation between each array item and the number
# ARRAY1-ARRAY2 (same dimensions!): Operation between items with the same position (a00*b00,a01*b01,...)
# ARRAY1-ARRAY2 (rows1x1 dimension): Operation between each array1 item and array2 item in the same column (a00*b00,a01*b01,...,a10*b00,a11*b01,...)

print(a3x4 - one3x4)
print(a3x4 - np.ones((1,4)))
print(a3x4 - 2)
print(a3x4 + one3x4) 
print(a3x4 * one3x4 * 2) 
print(np.ones((3,1)))
print(a3x4 * np.ones((3,1)))
print(one3x4 / (a3x4+1)) # (+1 because if first element=0 it causes ZeroDivideError)
print(one3x4 / 4)
print(a3x4**2)
print(np.sqrt(a3x4))
print(a3x4**(one3x4*2))
print(a3x4**(1/2))


print('\n -- MORE COMPLEX OPERATIONS --')
print(np.sin(a3x4))
print(np.cos(a3x4))
print(np.exp(a3x4)) # neperian exponentiation
print(np.exp(a3x4))
print(np.log(a3x4+1)) # neperain logarithm (+1 because if first element=0 it causes ZeroDivideError)
print(a3x4.dot(a4x3)) # MATRIX MULTIPLICATION cols1=rows2!
print(a3x4.dot(np.ones((4,10))))
print(a3x4.dot(np.ones((4,1))))


print('\n -- COMPARISON OPERATIONS --')
print(a3x4 == one3x4) # Comparison item by item with same position: return array dtype=bool
print((a3x4 == one3x4).all()) # True if all items=True/>0; False if any item=False/0
print(one3x4.all())
print(a3x4.all())


print('\n -- AGGREGATE OPERATIONS --')
# axis=0 : Column-wise
# axis=1 : Row-wise
print(a3x4.sum()) # Array-wise sumatory
print(a3x4.min())
print(a3x4.max())
print(a3x4.max(axis=0)) # Maxs of every column
print(a3x4.min(axis=1)) # Mins of every row
print(a3x4.cumsum()) # Cumulative sum 
print(a3x4.mean())
print('\n -- AGGREGATE MORE COMPLEX OPERATIONS --')
print(np.corrcoef(np.random.random((3,3)))) # Correlation coefficient
with np.printoptions(precision=3): # Options doesn't work!
    print(np.std(a3x4)) # Standard deviation

Array 3x4
(3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Array 4x3
(4, 3)
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Array 3x4 full of 1
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

 -- BASIC ARITHMETIC OPERATIONS --
[[-1.  0.  1.  2.]
 [ 3.  4.  5.  6.]
 [ 7.  8.  9. 10.]]
[[-1.  0.  1.  2.]
 [ 3.  4.  5.  6.]
 [ 7.  8.  9. 10.]]
[[-2 -1  0  1]
 [ 2  3  4  5]
 [ 6  7  8  9]]
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
[[ 0.  2.  4.  6.]
 [ 8. 10. 12. 14.]
 [16. 18. 20. 22.]]
[[1.]
 [1.]
 [1.]]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[1.         0.5        0.33333333 0.25      ]
 [0.2        0.16666667 0.14285714 0.125     ]
 [0.11111111 0.1        0.09090909 0.08333333]]
[[0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]]
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]
[[0.         1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974 2.64575131]
 [2.82842712 3.         3.16227766 3.31662479]]
[[

#### Copying arrays

In [78]:
array = np.ones((2,2), dtype = int)
array_copy = array.view() # View : Changes on view/array affect the other
print(array_copy)
array_copy = array.copy() # # Copy : Changes on copy/array don't affect the other
print(array_copy)

[[1 1]
 [1 1]]
[[1 1]
 [1 1]]


#### Sorting arrays

In [105]:
array_sorted = np.round(np.random.random((2,5)), decimals = 2)
print(array_sorted)
array_sorted.sort() # This method DOESN'T RETURN AN ARRAY, it modifies original array and RETURN NONE
print(array_sorted)
array_sorted[(1,1)]=2 # To see OK the difference between axis orders because random values are very similar
array_sorted.sort(axis=0) # Column-wise sorted
print(array_sorted)

[[0.35 0.08 0.42 0.39 0.23]
 [0.73 0.05 0.34 0.46 0.95]]
[[0.08 0.23 0.35 0.39 0.42]
 [0.05 0.34 0.46 0.73 0.95]]
[[0.05 0.23 0.35 0.39 0.42]
 [0.08 2.   0.46 0.73 0.95]]


#### Sub-setting, slicing and indexing arrays (obtaining subsettings from them!)

In [54]:
array = np.arange(16)
print('ARRAY 2D:')
array = array.reshape(4,-1)
print(array)
print('\n------')
print(array[1]) # Items of row 1, same as array[1,:]
print(array[1,2]) # Item row 1 col 2
print(array[:,1]) # Items of column 1
print(array[4:-1:-1,0:3:2]) # [TART:STOP:STEP, ...] If step<0 start>stop and endStop=-1!
print(array[1:3,0:2]) # Rows 1-3 Cols 0-2 (ends of ranges aren't included)
print(array[array<3]) # Firts row, cols<3
print(array[:,:-1]) # Remove last column 
print(array[-1:,:]) # Last row
print(array[:-1,:]) # Remove last row
print(array[::-1]) # Inverse row order, same as array[::-1,::]
print(array[::,::-1]) # Inverse col order
print(array[::-1,::-1]) # Inverse row and column order
print(np.flip(array, axis = 0)) # Inverse row order

print('\nARRAY 3D:')
array_3d = array.reshape(2,2,-1)
print3d(array_3d)
print(array_3d[-1,0,-1])
print('\n-----')
print(array_3d[1:,1:,2:]) # Rows 1-end Cols 1-end Items 2-end
print(array_3d[1:,1:,2:].shape) # x:, range -> It will generate a DIMENSION in resulting array
print(array_3d[1,1,2:].shape) # x, index -> It won't generate a dimension in resulting array

print('\nCOMBINED INDEXES:')
print(array[[1,2],[0,2]]) # Items in positions (1,0) (2,2) -> Dimension = 1x2
print(array[[1,2],:][:,[2,3]]) # Items in positions ((1,2) (1,3)) ((2,2) (2,3)) -> Dimension = 2x2 (same as [[1,2]][:,[2,2]])
print('---')
print(array_3d[[1,0],:,:][:,[0,1],:][:,:,[1,2]]) # Combining with 3D

ARRAY 2D:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

------
[4 5 6 7]
6
[ 1  5  9 13]
[]
[[4 5]
 [8 9]]
[0 1 2]
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]
[[12 13 14 15]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]
[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]
[[15 14 13 12]
 [11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]
[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]

ARRAY 3D:
[0 1 2 3] [4 5 6 7]
[ 8  9 10 11] [12 13 14 15]
11

-----
[[[14 15]]]
(1, 1, 2)
(2,)

COMBINED INDEXES:
[ 4 10]
[[ 6  7]
 [10 11]]
---
[[[ 9 10]
  [13 14]]

 [[ 1  2]
  [ 5  6]]]


#### Manipulating arrays

In [113]:
print('\nARRAY 3D:')
array_3d = np.arange(16).reshape(2,2,-1)
print3d(array_3d)
print('\nFLAT ARRAY:')
array = np.arange(20,24)
print(array)
print('\nCHANGING FEATURES:')
print3d(array_3d.T) # Transpose (permute dimensions) same as np.transpose(array_3d)
print(array_3d.ravel()) # Flat the array (1 unique row)
print3d(array_3d.reshape(8,2,-1)) # Change shape row=8 col=2 depth=auto-adjust
array_3d.resize((4,2,2)) # Change size of the ORIGINAL ARRAY (returns None)
print3d(array_3d)

print('\nHANDLING CONTENT:')
print(np.append(array,array_3d)) # Returns a flat array with whole items
print(np.insert(array_3d,2,99)) # (array,position,value to insert) Returns a flat array
array_insert = np.insert(array_3d,(3,4,3),[99,99,99])
print(array_insert) # Multi-item insert, if two indexes concur insert them consecutive and 'displace' next position! (i.e. pos4=pos5)
print(np.delete(array_insert,[3,4,3,3,3])) # Duplicate idexes are ignored


ARRAY 3D:
[0 1 2 3] [4 5 6 7]
[ 8  9 10 11] [12 13 14 15]

FLAT ARRAY:
[20 21 22 23]

CHANGING FEATURES:
[0 8] [ 4 12]
[1 9] [ 5 13]
[ 2 10] [ 6 14]
[ 3 11] [ 7 15]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[0] [1]
[2] [3]
[4] [5]
[6] [7]
[8] [9]
[10] [11]
[12] [13]
[14] [15]
[0 1] [2 3]
[4 5] [6 7]
[8 9] [10 11]
[12 13] [14 15]

HANDLING CONTENT:
[20 21 22 23  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[ 0  1 99  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[ 0  1  2 99 99  3 99  4  5  6  7  8  9 10 11 12 13 14 15]
[ 0  1  2  3 99  4  5  6  7  8  9 10 11 12 13 14 15]


#### Combining arrays

In [139]:
print('\nARRAY 3D:')
array_3d = np.arange(16).reshape(2,2,-1)
print3d(array_3d)
print(array_3d.shape)
print('\nFLAT ARRAY:')
array = np.arange(20,24)
print(array)
print('\n')
print(np.concatenate((array_3d, array_3d),axis=2)) # Arrays shape must match exactly
print3d(np.vstack((array_3d.reshape(4,2,-1),array)))


ARRAY 3D:
[0 1 2 3] [4 5 6 7]
[ 8  9 10 11] [12 13 14 15]
(2, 2, 4)

FLAT ARRAY:
[20 21 22 23]


[[[ 0  1  2  3  0  1  2  3]
  [ 4  5  6  7  4  5  6  7]]

 [[ 8  9 10 11  8  9 10 11]
  [12 13 14 15 12 13 14 15]]]


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 3 dimension(s) and the array at index 1 has 2 dimension(s)